In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url='https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_data =pd.read_csv(url,error_bad_lines=False)
fuel_data.describe(include='all')

record_id  utility_id_ferc1   report_year  \
count                    29523      29523.000000  29523.000000   
unique                   29523               NaN           NaN   
top     f1_fuel_2003_12_42_3_4               NaN           NaN   
freq                         1               NaN           NaN   
mean                       NaN        118.601836   2005.806050   
std                        NaN         74.178353      7.025483   
min                        NaN          1.000000   1994.000000   
25%                        NaN         55.000000   2000.000000   
50%                        NaN        122.000000   2006.000000   
75%                        NaN        176.000000   2012.000000   
max                        NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [3]:
arr = {
    'key':[3,5,7,9,43,],
    'cup':[1,2,3,4,5]
}
print(type(arr))

<class 'dict'>


In [4]:
print(arr.keys())
print(arr.values())
print(arr)

dict_keys(['key', 'cup'])
dict_values([[3, 5, 7, 9, 43], [1, 2, 3, 4, 5]])
{'key': [3, 5, 7, 9, 43], 'cup': [1, 2, 3, 4, 5]}


In [5]:
test_dict = { "geeks" : 7, "for" : 1, "geek" : 2 }
test_dict.update({"is":3})
print(test_dict)


{'geeks': 7, 'for': 1, 'geek': 2, 'is': 3}


In [6]:
set_test = [1,2,3,4,5,3,4,4,2,8]
print(set(set_test))

{1, 2, 3, 4, 5, 8}


In [7]:
c=[[2,'boy','but','vet','cat',6,7],[5,7,9,'it','is','a','boy']]
d=np.array(c)
print(d)
print(d.ndim)

[['2' 'boy' 'but' 'vet' 'cat' '6' '7']
 ['5' '7' '9' 'it' 'is' 'a' 'boy']]
2


In [8]:
np.random.random((2,4))

array([[0.06112442, 0.26759061, 0.37856494, 0.81995951],
       [0.85118904, 0.36498552, 0.31995775, 0.23868385]])

In [9]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
r=np.random.random((3,3))
b=np.identity(3)
print(r ** b)

[[0.18210597 1.         1.        ]
 [1.         0.42999546 1.        ]
 [1.         1.         0.76860095]]
